name: Docker Image CI

on:
  push:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag codeeducation:v1.0
      
    - name: Login Dockerhub
      run: docker login -u dionekist -p ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Login Dockerhub
      run: docker push dionekist/codeeducation:v1.0

    - name: Logout Dockerhub
      run: docker logout dionekist
